/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import logica.Gasolinera;

/**
 *
 * @author Jonathan
 */
public class Main extends javax.swing.JFrame implements ActionListener {
    
    String ventas = "";
    int gasolinaActualSuper;
    int sumaGasolinaSuper;
    
    public Main() {
        initComponents();
        Gasolinera gasolina = new Gasolinera();
        TxtSuper.setText(Integer.toString(gasolina.getBombaSuper()));
        TxtRegular.setText(Integer.toString(gasolina.getBombaRegular()));
        TxtDiesel.setText(Integer.toString(gasolina.getBombaDiesel()));
        BtnAgregar.addActionListener(this);
        BtnVender.addActionListener(this);
        BtnReporte.addActionListener(this);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtSuper = new javax.swing.JLabel();
        TxtRegular = new javax.swing.JLabel();
        TxtDiesel = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        BtnVender = new javax.swing.JButton();
        BtnReporte = new javax.swing.JButton();
        ComboGasolina = new javax.swing.JComboBox<>();
        TxtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboVenta = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        TxtVenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtReporte = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gasolinera Feliz");
        contenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 11, -1, -1));

        jLabel2.setText("SUPER");
        contenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setText("REGULAR");
        contenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel4.setText("DIESEL");
        contenido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        TxtSuper.setText("0000");
        contenido.add(TxtSuper, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        TxtRegular.setText("0000");
        contenido.add(TxtRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        TxtDiesel.setText("0000");
        contenido.add(TxtDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        BtnAgregar.setText("Agregar");
        contenido.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 103, 39));

        BtnVender.setText("Vender");
        contenido.add(BtnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 94, 39));

        BtnReporte.setText("Cargar reporte");
        contenido.add(BtnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, 40));

        ComboGasolina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Super", "Regular", "Diesel" }));
        contenido.add(ComboGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        contenido.add(TxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, -1));

        jLabel5.setText("Cantidad");
        contenido.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        ComboVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Super", "Regular", "Diesel" }));
        contenido.add(ComboVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel6.setText("Cantidad");
        contenido.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));
        contenido.add(TxtVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 160, -1));

        TxtReporte.setColumns(20);
        TxtReporte.setLineWrap(true);
        TxtReporte.setRows(5);
        jScrollPane1.setViewportView(TxtReporte);

        contenido.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 220, 130));

        getContentPane().add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnReporte;
    private javax.swing.JButton BtnVender;
    private javax.swing.JComboBox<String> ComboGasolina;
    private javax.swing.JComboBox<String> ComboVenta;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JLabel TxtDiesel;
    private javax.swing.JLabel TxtRegular;
    private javax.swing.JTextArea TxtReporte;
    private javax.swing.JLabel TxtSuper;
    private javax.swing.JTextField TxtVenta;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Gasolinera gasolina = new Gasolinera();
        if (e.getSource() == BtnAgregar) {
            if(ComboGasolina.getSelectedItem().toString().equals("Super")){
                gasolinaActualSuper = gasolina.getBombaSuper();
                sumaGasolinaSuper = Integer.parseInt(TxtCantidad.getText());
                
                gasolinaActualSuper = gasolinaActualSuper + sumaGasolinaSuper;
                gasolina.setBombaSuper(gasolinaActualSuper);
                TxtSuper.setText(Integer.toString(gasolinaActualSuper));
            }
            if(ComboGasolina.getSelectedItem().toString().equals("Regular")){
                int gasolinaActual = gasolina.getBombaRegular();
                int sumaGasolina = Integer.parseInt(TxtCantidad.getText());
                gasolinaActual = gasolinaActual + sumaGasolina;
                gasolina.setBombaSuper(gasolinaActual);
                TxtRegular.setText(Integer.toString(gasolinaActual));
            }
            if(ComboGasolina.getSelectedItem().toString().equals("Diesel")){
                int gasolinaActual = gasolina.getBombaDiesel();
                int sumaGasolina = Integer.parseInt(TxtCantidad.getText());
                gasolinaActual = gasolinaActual + sumaGasolina;
                gasolina.setBombaSuper(gasolinaActual);
                TxtDiesel.setText(Integer.toString(gasolinaActual));
            }
        }
        if (e.getSource() == BtnVender) {
            if(ComboVenta.getSelectedItem().toString().equals("Super")){
                int gasolinaActual = gasolina.getBombaSuper();
                int sumaGasolina = Integer.parseInt(TxtVenta.getText());
                gasolinaActual = gasolinaActual - sumaGasolina;
                
                ventas += Integer.toString(sumaGasolina) + " Super ";
                gasolina.setBombaSuper(gasolinaActual);
                TxtSuper.setText(Integer.toString(gasolinaActual));
            }
            if(ComboVenta.getSelectedItem().toString().equals("Regular")){
                int gasolinaActual = gasolina.getBombaRegular();
                int sumaGasolina = Integer.parseInt(TxtVenta.getText());
                gasolinaActual = gasolinaActual - sumaGasolina;
                ventas +=Integer.toString(sumaGasolina) + " Regular ";
                
                gasolina.setBombaRegular(gasolinaActual);
                TxtRegular.setText(Integer.toString(gasolinaActual));
            }
            if(ComboVenta.getSelectedItem().toString().equals("Diesel")){
                int gasolinaActual = gasolina.getBombaDiesel();
                int sumaGasolina = Integer.parseInt(TxtVenta.getText());
                gasolinaActual = gasolinaActual - sumaGasolina;
                ventas += Integer.toString(sumaGasolina) + " Diesel ";
                gasolina.setBombaDiesel(gasolinaActual);
                TxtDiesel.setText(Integer.toString(gasolinaActual));
            }
        }
        if (e.getSource() == BtnReporte) {
            TxtReporte.setText(ventas);
        }
    }
}
